name: Daily Auto Post GHOST IN THE LEGACY

on:
  schedule:
    # ë§¤ì¼ í•œêµ­ ì‹œê°„ 7ì‹œ 30ë¶„, 19ì‹œ 30ë¶„ (KST, UTC+9) ì‹¤í–‰
    - cron: '27 10 * * *'
    - cron: '27 22 * * *'
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ ì˜µì…˜

permissions:
  contents: write # ì €ì¥ì†Œì— í‘¸ì‹œí•˜ê¸° ìœ„í•œ ê¶Œí•œ í•„ìš”

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      # í•„ìš”í•œ ë¼ì´ë¸ŒëŸ¬ë¦¬ê°€ ìˆë‹¤ë©´ ì„¤ì¹˜ (ì˜ˆ: requests, openai ë“±)
      - name: Install dependencies
        run: pip install -r scripts/ghost_in_the_legacy/requirements.txt

      - name: Generate daily post
        env:
          # GitHubì— ì €ì¥ëœ SECRET_KEYë¥¼ ìŠ¤í¬ë¦½íŠ¸ì˜ í™˜ê²½ ë³€ìˆ˜ë¡œ ì£¼ì…
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_NOVEL }}
        run: python scripts/ghost_in_the_legacy/main.py

      # ë¹Œë“œ ì‹¤íŒ¨ ë©”ì„¸ì§€ ë°œì†¡
      - name: Send Build Failure Message
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Author: ${{github.actor}}
            
            Status: ğŸ˜± **Failure**
            
            Commit message: ${{ github.event.commits[0].message }}
            
            [link](https://github.com/${{ github.repository }}/actions)

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add _posts/
          git add scripts/ghost_in_the_legacy/
          # ë³€ê²½ì‚¬í•­ì´ ìˆì„ ë•Œë§Œ ì»¤ë°‹
          git commit -m "Add daily post [skip ci]" || exit 0
          git push


